### ISSUE TITLE
slug - Autoincrement in duplicate titles

### ISSUE THREAD

**Issue by emilioastarita** [tblobaum/mongoose-troop#16]
Hi, great collection of plugins. 
Any chance to add this feature to the slug plugin ?
Something like:

``` javascript
a = new Post({title:'hello world'});
b = new Post({title:'hello world'});
// save a and b
a.slug == 'hello-world';
b.slug == 'hello-world-1';
```

thanks!

**Comment by sorensen** [comment]
Slugs folow the same concept as UUID's, they should always be unique, it is an interesting thought to make them auto increment identical slugs. I could put an 'auto' option into the plugin for the schema hooks to be enabled or not upon configuration. 

I do believe it is upon the user and not the plugin to supply the logic for duplicate slugs, but you should at least be able to do so within the bounds of this plugin. would this solve the problem?

**Comment by emilioastarita** [comment]
Yes, I think it would be perfect. thanks!
