### ISSUE TITLE
created field is not created

### ISSUE THREAD

**Issue by panosru** [tblobaum/mongoose-troop#17]
Hello I try to use the `timestamp` plugin but only `modified` field is created the `created` time field is not... any idea?

**Comment by panosru** [comment]
Ok, as I saw it uses a `useVirtual` option in order to provide the created time based from _id but how I can I access that?

**Comment by panosru** [comment]
ok nvm I did a horible mistake :P 

I was passing the document through json and then I tried to access the virtual field from the json object, which obvisly faild :P

**Comment by tblobaum** [comment]
@panosru you can pass virtuals in mongoose (such as the created) with `doc.toObject({ /* getters: true, */ virtuals: true })` and then stringify the object or you can change the timestamp plugin so it doesn't use virtuals with `mySchema.plugin(troop.timestamp, { useVirtual: false })` -- but with this second option you'll be storing the created time data twice when you dont need to.

**Comment by panosru** [comment]
@tblobaum oh I didn't knew about this! Thanks a lot! :) :)
