### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by casey-chow** [tblobaum/mongoose-troop#21]
I'm trying to install this library onto my Windows machine, but when I do, it fails when attempting to install and compile `bcrypt`.

While I know that this is an issue with `bcrypt` and not `mongoose-troop`, I would really appreciate it if there was some way I or any Windows user could install this package. 

Thanks :-)

**Comment by tblobaum** [comment]
I'm going to make redis and bcrypt both optional dependencies, if you'd like you can then replace bcrypt with crypto, murmurhash3, or something else that works on your machine.

**Comment by dluces** [comment]
This should work now, as node.bcrypt.js has added support for windows using Win32OpenSSL:
See docs: https://github.com/ncb000gt/node.bcrypt.js

> For Windows you'll need http://slproweb.com/products/Win32OpenSSL.html installed to the default location of C:\OpenSSL-Win32

**Comment by tblobaum** [comment]
@dluces thanks for the update
