### ISSUE TITLE
Created Field not created...

### ISSUE THREAD

**Issue by kentcdodds** [tblobaum/mongoose-troop#36]
The modified field gets on just fine, but the created field doesn't get attached to any of the schemas I'm using the plugin for... I've tried providing a createdPath, and that didn't make a difference. The weird thing is when I print out the schema immediately after calling `.plugin` it shows the created field in the schema, however, none of the objects in my database have a`created` field, just a `modified` field. Am I missing something here?

This is how I'm using it: `schema.plugin(troop.timestamp);` where `schema` is one of my mongoose schemas. That's the right way to do it right?

**Comment by ThomasBormans** [comment]
Take a look at issue #17 if it is still necessary.

**Comment by kentcdodds** [comment]
I'm not working on a project that uses this anymore. Feel free to close this issue.
